Draft README (#37)
ExaWorks/SDK pull request #41
Opened 2021-05-06 21:23 UTC by j-woz

2021-05-07 00:45 UTC, dongahn requested changes
Superb. Super nit suggestions are in-lined below.

2021-05-07 00:45 UTC, dongahn commented on docker/swift-t/README.adoc
> +Dependencies are considered in the shell script install-deps.sh .
```suggestion
Dependencies are considered in the shell script `install-deps.sh`.
```

2021-05-07 00:45 UTC, dongahn commented on docker/swift-t/README.adoc
> +Swift/T is built from source in install-swift-t.sh .
```suggestion
Swift/T is built from source in `install-swift-t.sh`.
```

2021-05-07 00:45 UTC, dongahn commented on docker/swift-t/README.adoc
> +This is a standard build from GitHub.  sed is used to populate the Swift/T settings file before the build.
```suggestion
This is a standard build from the Swift/T GitHub repo. `sed` is used to populate the Swift/T settings file before the build.
```

2021-05-07 00:45 UTC, dongahn commented on docker/swift-t/README.adoc
> +See the following link for more information about compiling Swift/T: http://swift-lang.github.io/swift-t/guide.html#install_source
```suggestion
You can find more information about compiling Swift/T [here](http://swift-lang.github.io/swift-t/guide.html#install_source)
```

2021-05-07 00:45 UTC, dongahn commented on docker/swift-t/README.adoc
> +Currently, a small test suite is run from shell script test-sanity.sh .
```suggestion
Currently, a small test suite is run from shell script `test-sanity.sh`.
```

2021-05-07 16:33 UTC, mturilli reviewed
Maybe add a note+link to Swift/T examples and overall documentation? Otherwise, LGTM.

2021-05-07 17:29 UTC, j-woz commented
Good idea, I will add that.

2021-05-07 17:59 UTC, j-woz commented
Ok those items are in as "Further information"

2021-05-07 17:59 UTC, mturilli approved these changes
LGTM!

2021-05-10 16:31 UTC, j-woz commented
Sure.

2021-05-17 20:16 UTC, j-woz commented
Ok- I think 31a6bf78 is the single commit for this README

2021-05-17 20:32 UTC, dongahn commented
Thanks @j-woz. It seems this PR has all other changes you are currently making? Did you mean to create a PR with a single commit instead?

Probably the easiest way to do this is to create a branch in your fork out of the upstream master and add that single commit and do force a push, I think.

2021-05-17 22:02 UTC, closed without merging